# auto-generated TEE configuration file
# TEE version 3.15.0-9-g1bb3e73b-dev
set(CFG_AES_GCM_TABLE_BASED y)
set(CFG_BOOT_SECONDARY_REQUEST y)
set(CFG_CC_OPT_LEVEL 0)
set(CFG_COMPAT_GP10_DES y)
# CFG_CORE_ASLR is not set 
# CFG_CORE_BGET_BESTFIT is not set 
set(CFG_CORE_BIGNUM_MAX_BITS 4096)
set(CFG_CORE_CLUSTER_SHIFT 2)
# CFG_CORE_DEBUG_CHECK_STACKS is not set 
# CFG_CORE_DUMP_OOM is not set 
set(CFG_CORE_DYN_SHM y)
set(CFG_CORE_HEAP_SIZE 65536)
set(CFG_CORE_HUK_SUBKEY_COMPAT y)
# CFG_CORE_LARGE_PHYS_ADDR is not set 
set(CFG_CORE_MAX_SYSCALL_RECURSION 4)
set(CFG_CORE_MBEDTLS_MPI y)
set(CFG_CORE_NEX_HEAP_SIZE 16384)
# CFG_CORE_PAGE_TAG_AND_IV is not set 
set(CFG_CORE_RESERVED_SHM y)
set(CFG_CORE_RISCV64_PA_BITS 32)
# CFG_CORE_RODATA_NOEXEC is not set 
set(CFG_CORE_RWDATA_NOEXEC y)
# CFG_CORE_SANITIZE_KADDRESS is not set 
# CFG_CORE_SANITIZE_UNDEFINED is not set 
set(CFG_CORE_THREAD_SHIFT 0)
# CFG_CORE_TPM_EVENT_LOG is not set 
set(CFG_CORE_TZSRAM_EMUL_SIZE 458752)
# CFG_CORE_UNMAP_CORE_AT_EL0 is not set 
# CFG_CORE_WORKAROUND_NSITR_CACHE_PRIME is not set 
# CFG_CORE_WORKAROUND_SPECTRE_BP is not set 
# CFG_CORE_WORKAROUND_SPECTRE_BP_SEC is not set 
set(CFG_CRYPTO y)
set(CFG_CRYPTOLIB_DIR core/lib/libtomcrypt)
set(CFG_CRYPTOLIB_NAME tomcrypt)
set(CFG_CRYPTOLIB_NAME_tomcrypt y)
set(CFG_CRYPTO_AES y)
# CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB is not set 
set(CFG_CRYPTO_CBC y)
set(CFG_CRYPTO_CBC_MAC y)
set(CFG_CRYPTO_CBC_MAC_BUNDLE_BLOCKS 64)
set(CFG_CRYPTO_CCM y)
set(CFG_CRYPTO_CMAC y)
set(CFG_CRYPTO_CONCAT_KDF y)
set(CFG_CRYPTO_CTR y)
set(CFG_CRYPTO_CTS y)
set(CFG_CRYPTO_DES y)
set(CFG_CRYPTO_DH y)
set(CFG_CRYPTO_DSA y)
set(CFG_CRYPTO_ECB y)
set(CFG_CRYPTO_ECC y)
set(CFG_CRYPTO_GCM y)
set(CFG_CRYPTO_HKDF y)
set(CFG_CRYPTO_HMAC y)
set(CFG_CRYPTO_MD5 y)
set(CFG_CRYPTO_PBKDF2 y)
set(CFG_CRYPTO_RSA y)
set(CFG_CRYPTO_RSASSA_NA1 y)
set(CFG_CRYPTO_SHA1 y)
set(CFG_CRYPTO_SHA224 y)
set(CFG_CRYPTO_SHA256 y)
set(CFG_CRYPTO_SHA384 y)
set(CFG_CRYPTO_SHA512 y)
set(CFG_CRYPTO_SHA512_256 y)
set(CFG_CRYPTO_SIZE_OPTIMIZATION y)
set(CFG_CRYPTO_SM2_DSA y)
set(CFG_CRYPTO_SM2_KEP y)
set(CFG_CRYPTO_SM2_PKE y)
set(CFG_CRYPTO_SM3 y)
set(CFG_CRYPTO_SM4 y)
set(CFG_CRYPTO_XTS y)
set(CFG_DEBUG_INFO y)
set(CFG_DEVICE_ENUM_PTA y)
set(CFG_DT y)
set(CFG_DTB_MAX_SIZE 0x100000)
set(CFG_DT_ADDR 0x1f00000)
# CFG_EARLY_TA is not set 
set(CFG_EARLY_TA_COMPRESS y)
# CFG_EMBED_DTB is not set 
set(CFG_ENABLE_EMBEDDED_TESTS y)
set(CFG_ENABLE_SCTLR_Z y)
# CFG_EXTERNAL_DTB_OVERLAY is not set 
set(CFG_FTRACE_BUF_WHEN_FULL shift)
# CFG_FTRACE_SUPPORT is not set 
set(CFG_FTRACE_US_MS 10000)
# CFG_GENERATE_DTB_OVERLAY is not set 
# CFG_GP_SOCKETS is not set 
# CFG_HWRNG_PTA is not set 
set(CFG_HWSUPP_MEM_PERM_PXN y)
set(CFG_HWSUPP_MEM_PERM_WXN y)
set(CFG_IOPMP y)
set(CFG_KERN_LINKER_ARCH riscv)
set(CFG_KERN_LINKER_FORMAT elf64-littleriscv)
set(CFG_LIBUTILS_WITH_ISOC y)
set(CFG_LIGHT_UART y)
# CFG_LOCKDEP is not set 
set(CFG_LOCKDEP_RECORD_STACK y)
set(CFG_LPAE_ADDR_SPACE_BITS 32)
set(CFG_LTC_OPTEE_THREAD y)
set(CFG_MMAP_REGIONS 13)
set(CFG_MSG_LONG_PREFIX_MASK 0x1a)
set(CFG_NUM_THREADS 4)
set(CFG_OPTEE_REVISION_MAJOR 3)
set(CFG_OPTEE_REVISION_MINOR 15)
set(CFG_OS_REV_REPORTS_GIT_SHA1 y)
# CFG_PAGED_USER_TA is not set 
set(CFG_PKCS11_TA_ALLOW_DIGEST_KEY y)
set(CFG_PKCS11_TA_AUTH_TEE_IDENTITY y)
set(CFG_PKCS11_TA_HEAP_SIZE (16 * 1024))
set(CFG_PKCS11_TA_TOKEN_COUNT 3)
# CFG_PL011 is not set 
set(CFG_PLIC y)
set(CFG_PREALLOC_RPC_CACHE y)
set(CFG_PSCI_RV32 y)
set(CFG_REE_FS y)
# CFG_REE_FS_ALLOW_RESET is not set 
set(CFG_REE_FS_TA y)
# CFG_REE_FS_TA_BUFFERED is not set 
set(CFG_RESERVED_VASPACE_SIZE (1024 * 1024 * 10))
# CFG_RISCV32_core is not set 
set(CFG_RISCV32_ta_riscv32 y)
set(CFG_RISCV64_core y)
set(CFG_RISCV64_ldelf y)
set(CFG_RISCV64_ta_riscv64 y)
# CFG_RPMB_FS is not set 
set(CFG_RPMB_FS_CACHE_ENTRIES 0)
# CFG_RPMB_FS_DEBUG_DATA is not set 
set(CFG_RPMB_FS_DEV_ID 0)
set(CFG_RPMB_FS_RD_ENTRIES 8)
# CFG_RPMB_RESET_FAT is not set 
# CFG_RPMB_TESTKEY is not set 
# CFG_RPMB_WRITE_KEY is not set 
# CFG_SCMI_MSG_CLOCK is not set 
# CFG_SCMI_MSG_DRIVERS is not set 
# CFG_SCMI_MSG_RESET_DOMAIN is not set 
# CFG_SCMI_MSG_SMT is not set 
# CFG_SCMI_MSG_VOLTAGE_DOMAIN is not set 
# CFG_SCMI_PTA is not set 
# CFG_SCTLR_ALIGNMENT_CHECK is not set 
set(CFG_SECSTOR_TA y)
set(CFG_SECSTOR_TA_MGMT_PTA y)
# CFG_SECURE_DATA_PATH is not set 
# CFG_SECURE_PARTITION is not set 
# CFG_SECURE_TIME_SOURCE_CNTPCT is not set 
set(CFG_SECURE_TIME_SOURCE_REE y)
set(CFG_SHMEM_SIZE 0x00200000)
set(CFG_SHMEM_START 0xfee00000)
# CFG_SHOW_CONF_ON_BOOT is not set 
set(CFG_SM_NO_CYCLE_COUNTING y)
set(CFG_STACK_THREAD_EXTRA 0)
set(CFG_STACK_TMP_EXTRA 0)
# CFG_SYSCALL_FTRACE is not set 
# CFG_SYSCALL_WRAPPERS_MCOUNT is not set 
set(CFG_SYSTEM_PTA y)
set(CFG_TA_ASLR y)
set(CFG_TA_ASLR_MAX_OFFSET_PAGES 128)
set(CFG_TA_ASLR_MIN_OFFSET_PAGES 0)
set(CFG_TA_BGET_TEST y)
set(CFG_TA_BIGNUM_MAX_BITS 2048)
# CFG_TA_FLOAT_SUPPORT is not set 
# CFG_TA_GPROF_SUPPORT is not set 
set(CFG_TA_MBEDTLS y)
set(CFG_TA_MBEDTLS_MPI y)
set(CFG_TA_MBEDTLS_SELF_TEST y)
set(CFG_TA_STRICT_ANNOTATION_CHECKS y)
set(CFG_TEE_API_VERSION GPD-1.1-dev)
# CFG_TEE_BENCHMARK is not set 
set(CFG_TEE_CORE_DEBUG y)
set(CFG_TEE_CORE_EMBED_INTERNAL_TESTS y)
set(CFG_TEE_CORE_LOG_LEVEL 3)
# CFG_TEE_CORE_MALLOC_DEBUG is not set 
set(CFG_TEE_CORE_NB_CORE 4)
set(CFG_TEE_CORE_TA_TRACE y)
set(CFG_TEE_FW_IMPL_VERSION FW_IMPL_UNDEF)
set(CFG_TEE_FW_MANUFACTURER FW_MAN_UNDEF)
set(CFG_TEE_IMPL_DESCR OPTEE)
set(CFG_TEE_MANUFACTURER LINARO)
set(CFG_TEE_RAM_VA_SIZE 0x00200000)
set(CFG_TEE_SDP_MEM_SIZE 0x00400000)
set(CFG_TEE_TA_LOG_LEVEL 1)
# CFG_TEE_TA_MALLOC_DEBUG is not set 
set(CFG_TZDRAM_SIZE 0x01000000)
set(CFG_TZDRAM_START 0xff000000)
# CFG_ULIBS_MCOUNT is not set 
# CFG_ULIBS_SHARED is not set 
set(CFG_UNWIND y)
# CFG_VIRTUALIZATION is not set 
set(CFG_WITH_ARM_TRUSTED_FW y)
# CFG_WITH_PAGER is not set 
set(CFG_WITH_SOFTWARE_PRNG y)
set(CFG_WITH_STACK_CANARIES y)
set(CFG_WITH_STATS y)
# CFG_WITH_STMM_SP is not set 
set(CFG_WITH_SV39 y)
set(CFG_WITH_USER_TA y)
# CFG_WITH_VFP is not set 
set(PLATFORM_FLAVOR light)
set(PLATFORM_FLAVOR_light y)
set(PLATFORM_light y)
set(_CFG_CORE_LTC_ACIPHER y)
set(_CFG_CORE_LTC_AES y)
# _CFG_CORE_LTC_AES_ACCEL is not set 
set(_CFG_CORE_LTC_AES_DESC y)
set(_CFG_CORE_LTC_ASN1 y)
set(_CFG_CORE_LTC_AUTHENC y)
set(_CFG_CORE_LTC_BIGNUM_MAX_BITS 4096)
set(_CFG_CORE_LTC_CBC y)
set(_CFG_CORE_LTC_CBC_MAC y)
set(_CFG_CORE_LTC_CCM y)
# _CFG_CORE_LTC_CE is not set 
set(_CFG_CORE_LTC_CIPHER y)
set(_CFG_CORE_LTC_CMAC y)
set(_CFG_CORE_LTC_CTR y)
set(_CFG_CORE_LTC_CTS y)
set(_CFG_CORE_LTC_DES y)
set(_CFG_CORE_LTC_DH y)
set(_CFG_CORE_LTC_DSA y)
set(_CFG_CORE_LTC_ECB y)
set(_CFG_CORE_LTC_ECC y)
set(_CFG_CORE_LTC_HASH y)
set(_CFG_CORE_LTC_HMAC y)
# _CFG_CORE_LTC_HWSUPP_PMULL is not set 
set(_CFG_CORE_LTC_MAC y)
set(_CFG_CORE_LTC_MD5 y)
set(_CFG_CORE_LTC_MPI y)
set(_CFG_CORE_LTC_OPTEE_THREAD y)
# _CFG_CORE_LTC_PAGER is not set 
set(_CFG_CORE_LTC_RSA y)
set(_CFG_CORE_LTC_SHA1 y)
# _CFG_CORE_LTC_SHA1_ACCEL is not set 
set(_CFG_CORE_LTC_SHA224 y)
set(_CFG_CORE_LTC_SHA256 y)
# _CFG_CORE_LTC_SHA256_ACCEL is not set 
set(_CFG_CORE_LTC_SHA256_DESC y)
set(_CFG_CORE_LTC_SHA384 y)
set(_CFG_CORE_LTC_SHA384_DESC y)
set(_CFG_CORE_LTC_SHA512 y)
set(_CFG_CORE_LTC_SHA512_256 y)
set(_CFG_CORE_LTC_SHA512_DESC y)
set(_CFG_CORE_LTC_SIZE_OPTIMIZATION y)
set(_CFG_CORE_LTC_SM2_DSA y)
set(_CFG_CORE_LTC_SM2_KEP y)
set(_CFG_CORE_LTC_SM2_PKE y)
# _CFG_CORE_LTC_VFP is not set 
set(_CFG_CORE_LTC_XTS y)
set(_CFG_FTRACE_BUF_WHEN_FULL_shift y)
# _CFG_USE_DTB_OVERLAY is not set 
